### PR TITLE
Treat heterogenous lists of exact length as tuples

### PR DESCRIPTION
**Pull request by untitaker**
https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation

### CODE REVIEW

**Comment by untitaker** [comment]
@bsamseth could you take a look at this? I think this is a relatively straightfoward fix and currently blocks us at getsentry from adopting (as otherwise the library crashes).

**Comment by bsamseth** [comment]
Hi! Sorry about the late response, I didn't get a notification about this until you tagged me in the comment. (If there is a next time, request a review by me and I will see it right away!)

Thanks a lot for this PR. This seems like a clear cut addition, so I will merge it in right away. New release coming up. Thanks again for chipping in! Hope you are able to benefit from this project now.

**Comment by bsamseth** [comment]
New release on PyPI: https://pypi.org/project/jsonschema-typed-v2/

**Comment by untitaker** [comment]
Thank you very much! 

EDIT: Don't delete fork branch to not break dependent projects.

**Pull request merged**
